package team.a9043.sign_in_system.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import team.a9043.sign_in_system.pojo.SisContact;
import team.a9043.sign_in_system.pojo.SisContactExample;

public interface SisContactMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_contact
     *
     * @mbg.generated Fri Sep 14 12:05:13 CST 2018
     */
    long countByExample(SisContactExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_contact
     *
     * @mbg.generated Fri Sep 14 12:05:13 CST 2018
     */
    int deleteByExample(SisContactExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_contact
     *
     * @mbg.generated Fri Sep 14 12:05:13 CST 2018
     */
    int deleteByPrimaryKey(Integer sctId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_contact
     *
     * @mbg.generated Fri Sep 14 12:05:13 CST 2018
     */
    int insert(SisContact record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_contact
     *
     * @mbg.generated Fri Sep 14 12:05:13 CST 2018
     */
    int insertSelective(SisContact record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_contact
     *
     * @mbg.generated Fri Sep 14 12:05:13 CST 2018
     */
    List<SisContact> selectByExample(SisContactExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_contact
     *
     * @mbg.generated Fri Sep 14 12:05:13 CST 2018
     */
    SisContact selectByPrimaryKey(Integer sctId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_contact
     *
     * @mbg.generated Fri Sep 14 12:05:13 CST 2018
     */
    int updateByExampleSelective(@Param("record") SisContact record, @Param("example") SisContactExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_contact
     *
     * @mbg.generated Fri Sep 14 12:05:13 CST 2018
     */
    int updateByExample(@Param("record") SisContact record, @Param("example") SisContactExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_contact
     *
     * @mbg.generated Fri Sep 14 12:05:13 CST 2018
     */
    int updateByPrimaryKeySelective(SisContact record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_contact
     *
     * @mbg.generated Fri Sep 14 12:05:13 CST 2018
     */
    int updateByPrimaryKey(SisContact record);
}