package team.a9043.sign_in_system.pojo;

import java.util.ArrayList;
import java.util.List;

public class SisContactExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sis_contact
     *
     * @mbg.generated Fri Sep 14 12:05:13 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sis_contact
     *
     * @mbg.generated Fri Sep 14 12:05:13 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sis_contact
     *
     * @mbg.generated Fri Sep 14 12:05:13 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_contact
     *
     * @mbg.generated Fri Sep 14 12:05:13 CST 2018
     */
    public SisContactExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_contact
     *
     * @mbg.generated Fri Sep 14 12:05:13 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_contact
     *
     * @mbg.generated Fri Sep 14 12:05:13 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_contact
     *
     * @mbg.generated Fri Sep 14 12:05:13 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_contact
     *
     * @mbg.generated Fri Sep 14 12:05:13 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_contact
     *
     * @mbg.generated Fri Sep 14 12:05:13 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_contact
     *
     * @mbg.generated Fri Sep 14 12:05:13 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_contact
     *
     * @mbg.generated Fri Sep 14 12:05:13 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_contact
     *
     * @mbg.generated Fri Sep 14 12:05:13 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_contact
     *
     * @mbg.generated Fri Sep 14 12:05:13 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_contact
     *
     * @mbg.generated Fri Sep 14 12:05:13 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sis_contact
     *
     * @mbg.generated Fri Sep 14 12:05:13 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSctIdIsNull() {
            addCriterion("sct_id is null");
            return (Criteria) this;
        }

        public Criteria andSctIdIsNotNull() {
            addCriterion("sct_id is not null");
            return (Criteria) this;
        }

        public Criteria andSctIdEqualTo(Integer value) {
            addCriterion("sct_id =", value, "sctId");
            return (Criteria) this;
        }

        public Criteria andSctIdNotEqualTo(Integer value) {
            addCriterion("sct_id <>", value, "sctId");
            return (Criteria) this;
        }

        public Criteria andSctIdGreaterThan(Integer value) {
            addCriterion("sct_id >", value, "sctId");
            return (Criteria) this;
        }

        public Criteria andSctIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("sct_id >=", value, "sctId");
            return (Criteria) this;
        }

        public Criteria andSctIdLessThan(Integer value) {
            addCriterion("sct_id <", value, "sctId");
            return (Criteria) this;
        }

        public Criteria andSctIdLessThanOrEqualTo(Integer value) {
            addCriterion("sct_id <=", value, "sctId");
            return (Criteria) this;
        }

        public Criteria andSctIdIn(List<Integer> values) {
            addCriterion("sct_id in", values, "sctId");
            return (Criteria) this;
        }

        public Criteria andSctIdNotIn(List<Integer> values) {
            addCriterion("sct_id not in", values, "sctId");
            return (Criteria) this;
        }

        public Criteria andSctIdBetween(Integer value1, Integer value2) {
            addCriterion("sct_id between", value1, value2, "sctId");
            return (Criteria) this;
        }

        public Criteria andSctIdNotBetween(Integer value1, Integer value2) {
            addCriterion("sct_id not between", value1, value2, "sctId");
            return (Criteria) this;
        }

        public Criteria andSctNameIsNull() {
            addCriterion("sct_name is null");
            return (Criteria) this;
        }

        public Criteria andSctNameIsNotNull() {
            addCriterion("sct_name is not null");
            return (Criteria) this;
        }

        public Criteria andSctNameEqualTo(String value) {
            addCriterion("sct_name =", value, "sctName");
            return (Criteria) this;
        }

        public Criteria andSctNameNotEqualTo(String value) {
            addCriterion("sct_name <>", value, "sctName");
            return (Criteria) this;
        }

        public Criteria andSctNameGreaterThan(String value) {
            addCriterion("sct_name >", value, "sctName");
            return (Criteria) this;
        }

        public Criteria andSctNameGreaterThanOrEqualTo(String value) {
            addCriterion("sct_name >=", value, "sctName");
            return (Criteria) this;
        }

        public Criteria andSctNameLessThan(String value) {
            addCriterion("sct_name <", value, "sctName");
            return (Criteria) this;
        }

        public Criteria andSctNameLessThanOrEqualTo(String value) {
            addCriterion("sct_name <=", value, "sctName");
            return (Criteria) this;
        }

        public Criteria andSctNameLike(String value) {
            addCriterion("sct_name like", value, "sctName");
            return (Criteria) this;
        }

        public Criteria andSctNameNotLike(String value) {
            addCriterion("sct_name not like", value, "sctName");
            return (Criteria) this;
        }

        public Criteria andSctNameIn(List<String> values) {
            addCriterion("sct_name in", values, "sctName");
            return (Criteria) this;
        }

        public Criteria andSctNameNotIn(List<String> values) {
            addCriterion("sct_name not in", values, "sctName");
            return (Criteria) this;
        }

        public Criteria andSctNameBetween(String value1, String value2) {
            addCriterion("sct_name between", value1, value2, "sctName");
            return (Criteria) this;
        }

        public Criteria andSctNameNotBetween(String value1, String value2) {
            addCriterion("sct_name not between", value1, value2, "sctName");
            return (Criteria) this;
        }

        public Criteria andSctContactIsNull() {
            addCriterion("sct_contact is null");
            return (Criteria) this;
        }

        public Criteria andSctContactIsNotNull() {
            addCriterion("sct_contact is not null");
            return (Criteria) this;
        }

        public Criteria andSctContactEqualTo(String value) {
            addCriterion("sct_contact =", value, "sctContact");
            return (Criteria) this;
        }

        public Criteria andSctContactNotEqualTo(String value) {
            addCriterion("sct_contact <>", value, "sctContact");
            return (Criteria) this;
        }

        public Criteria andSctContactGreaterThan(String value) {
            addCriterion("sct_contact >", value, "sctContact");
            return (Criteria) this;
        }

        public Criteria andSctContactGreaterThanOrEqualTo(String value) {
            addCriterion("sct_contact >=", value, "sctContact");
            return (Criteria) this;
        }

        public Criteria andSctContactLessThan(String value) {
            addCriterion("sct_contact <", value, "sctContact");
            return (Criteria) this;
        }

        public Criteria andSctContactLessThanOrEqualTo(String value) {
            addCriterion("sct_contact <=", value, "sctContact");
            return (Criteria) this;
        }

        public Criteria andSctContactLike(String value) {
            addCriterion("sct_contact like", value, "sctContact");
            return (Criteria) this;
        }

        public Criteria andSctContactNotLike(String value) {
            addCriterion("sct_contact not like", value, "sctContact");
            return (Criteria) this;
        }

        public Criteria andSctContactIn(List<String> values) {
            addCriterion("sct_contact in", values, "sctContact");
            return (Criteria) this;
        }

        public Criteria andSctContactNotIn(List<String> values) {
            addCriterion("sct_contact not in", values, "sctContact");
            return (Criteria) this;
        }

        public Criteria andSctContactBetween(String value1, String value2) {
            addCriterion("sct_contact between", value1, value2, "sctContact");
            return (Criteria) this;
        }

        public Criteria andSctContactNotBetween(String value1, String value2) {
            addCriterion("sct_contact not between", value1, value2, "sctContact");
            return (Criteria) this;
        }

        public Criteria andSctContentIsNull() {
            addCriterion("sct_content is null");
            return (Criteria) this;
        }

        public Criteria andSctContentIsNotNull() {
            addCriterion("sct_content is not null");
            return (Criteria) this;
        }

        public Criteria andSctContentEqualTo(String value) {
            addCriterion("sct_content =", value, "sctContent");
            return (Criteria) this;
        }

        public Criteria andSctContentNotEqualTo(String value) {
            addCriterion("sct_content <>", value, "sctContent");
            return (Criteria) this;
        }

        public Criteria andSctContentGreaterThan(String value) {
            addCriterion("sct_content >", value, "sctContent");
            return (Criteria) this;
        }

        public Criteria andSctContentGreaterThanOrEqualTo(String value) {
            addCriterion("sct_content >=", value, "sctContent");
            return (Criteria) this;
        }

        public Criteria andSctContentLessThan(String value) {
            addCriterion("sct_content <", value, "sctContent");
            return (Criteria) this;
        }

        public Criteria andSctContentLessThanOrEqualTo(String value) {
            addCriterion("sct_content <=", value, "sctContent");
            return (Criteria) this;
        }

        public Criteria andSctContentLike(String value) {
            addCriterion("sct_content like", value, "sctContent");
            return (Criteria) this;
        }

        public Criteria andSctContentNotLike(String value) {
            addCriterion("sct_content not like", value, "sctContent");
            return (Criteria) this;
        }

        public Criteria andSctContentIn(List<String> values) {
            addCriterion("sct_content in", values, "sctContent");
            return (Criteria) this;
        }

        public Criteria andSctContentNotIn(List<String> values) {
            addCriterion("sct_content not in", values, "sctContent");
            return (Criteria) this;
        }

        public Criteria andSctContentBetween(String value1, String value2) {
            addCriterion("sct_content between", value1, value2, "sctContent");
            return (Criteria) this;
        }

        public Criteria andSctContentNotBetween(String value1, String value2) {
            addCriterion("sct_content not between", value1, value2, "sctContent");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sis_contact
     *
     * @mbg.generated do_not_delete_during_merge Fri Sep 14 12:05:13 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sis_contact
     *
     * @mbg.generated Fri Sep 14 12:05:13 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}