package team.a9043.sign_in_system.pojo;

public class SisMonitorTrans extends SisMonitorTransKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sis_monitor_trans.smt_agree
     *
     * @mbg.generated Mon Aug 27 13:08:41 CST 2018
     */
    private Integer smtAgree;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sis_monitor_trans.su_id
     *
     * @mbg.generated Mon Aug 27 13:08:41 CST 2018
     */
    private String suId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sis_monitor_trans.smt_status
     *
     * @mbg.generated Mon Aug 27 13:08:41 CST 2018
     */
    private Integer smtStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sis_monitor_trans.smt_agree
     *
     * @return the value of sis_monitor_trans.smt_agree
     *
     * @mbg.generated Mon Aug 27 13:08:41 CST 2018
     */
    public Integer getSmtAgree() {
        return smtAgree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sis_monitor_trans.smt_agree
     *
     * @param smtAgree the value for sis_monitor_trans.smt_agree
     *
     * @mbg.generated Mon Aug 27 13:08:41 CST 2018
     */
    public void setSmtAgree(Integer smtAgree) {
        this.smtAgree = smtAgree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sis_monitor_trans.su_id
     *
     * @return the value of sis_monitor_trans.su_id
     *
     * @mbg.generated Mon Aug 27 13:08:41 CST 2018
     */
    public String getSuId() {
        return suId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sis_monitor_trans.su_id
     *
     * @param suId the value for sis_monitor_trans.su_id
     *
     * @mbg.generated Mon Aug 27 13:08:41 CST 2018
     */
    public void setSuId(String suId) {
        this.suId = suId == null ? null : suId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sis_monitor_trans.smt_status
     *
     * @return the value of sis_monitor_trans.smt_status
     *
     * @mbg.generated Mon Aug 27 13:08:41 CST 2018
     */
    public Integer getSmtStatus() {
        return smtStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sis_monitor_trans.smt_status
     *
     * @param smtStatus the value for sis_monitor_trans.smt_status
     *
     * @mbg.generated Mon Aug 27 13:08:41 CST 2018
     */
    public void setSmtStatus(Integer smtStatus) {
        this.smtStatus = smtStatus;
    }
}