package team.a9043.sign_in_system.pojo;

import io.swagger.annotations.ApiModelProperty;
import team.a9043.sign_in_system.exception.String2ValueException;

import javax.validation.constraints.NotNull;

public class SisMonitorTrans extends SisMonitorTransKey {
    public enum SmtStatus {
        UNTREATED(), AGREE(), DISAGREE();

        public static Integer lowercase2Value(String value) throws String2ValueException {
            switch (value) {
                case "untreated":
                    return UNTREATED.ordinal();
                case "agree":
                    return AGREE.ordinal();
                case "disagree":
                    return DISAGREE.ordinal();
                default:
                    throw new String2ValueException("No enum: " + value);
            }
        }
    }
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sis_monitor_trans.su_id
     *
     * @mbg.generated Tue Aug 28 21:51:04 CST 2018
     */
    @ApiModelProperty("转接人")
    @NotNull
    private String suId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sis_monitor_trans.smt_status
     *
     * @mbg.generated Tue Aug 28 21:51:04 CST 2018
     */
    @ApiModelProperty(value = "转接状态",
    allowableValues = "0(untreated), 1(agree), 2(disagree)")
    private Integer smtStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sis_monitor_trans.su_id
     *
     * @return the value of sis_monitor_trans.su_id
     *
     * @mbg.generated Tue Aug 28 21:51:04 CST 2018
     */
    public String getSuId() {
        return suId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sis_monitor_trans.su_id
     *
     * @param suId the value for sis_monitor_trans.su_id
     *
     * @mbg.generated Tue Aug 28 21:51:04 CST 2018
     */
    public void setSuId(String suId) {
        this.suId = suId == null ? null : suId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sis_monitor_trans.smt_status
     *
     * @return the value of sis_monitor_trans.smt_status
     *
     * @mbg.generated Tue Aug 28 21:51:04 CST 2018
     */
    public Integer getSmtStatus() {
        return smtStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sis_monitor_trans.smt_status
     *
     * @param smtStatus the value for sis_monitor_trans.smt_status
     *
     * @mbg.generated Tue Aug 28 21:51:04 CST 2018
     */
    public void setSmtStatus(Integer smtStatus) {
        this.smtStatus = smtStatus;
    }
}