package team.a9043.sign_in_system.pojo;

public class SisSignInDetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sis_sign_in_detail.ssid_id
     *
     * @mbg.generated Mon Aug 27 13:08:41 CST 2018
     */
    private Integer ssidId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sis_sign_in_detail.ssid_status
     *
     * @mbg.generated Mon Aug 27 13:08:41 CST 2018
     */
    private Boolean ssidStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sis_sign_in_detail.ssi_id
     *
     * @mbg.generated Mon Aug 27 13:08:41 CST 2018
     */
    private Integer ssiId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sis_sign_in_detail.su_id
     *
     * @mbg.generated Mon Aug 27 13:08:41 CST 2018
     */
    private String suId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sis_sign_in_detail.ssid_id
     *
     * @return the value of sis_sign_in_detail.ssid_id
     *
     * @mbg.generated Mon Aug 27 13:08:41 CST 2018
     */
    public Integer getSsidId() {
        return ssidId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sis_sign_in_detail.ssid_id
     *
     * @param ssidId the value for sis_sign_in_detail.ssid_id
     *
     * @mbg.generated Mon Aug 27 13:08:41 CST 2018
     */
    public void setSsidId(Integer ssidId) {
        this.ssidId = ssidId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sis_sign_in_detail.ssid_status
     *
     * @return the value of sis_sign_in_detail.ssid_status
     *
     * @mbg.generated Mon Aug 27 13:08:41 CST 2018
     */
    public Boolean getSsidStatus() {
        return ssidStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sis_sign_in_detail.ssid_status
     *
     * @param ssidStatus the value for sis_sign_in_detail.ssid_status
     *
     * @mbg.generated Mon Aug 27 13:08:41 CST 2018
     */
    public void setSsidStatus(Boolean ssidStatus) {
        this.ssidStatus = ssidStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sis_sign_in_detail.ssi_id
     *
     * @return the value of sis_sign_in_detail.ssi_id
     *
     * @mbg.generated Mon Aug 27 13:08:41 CST 2018
     */
    public Integer getSsiId() {
        return ssiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sis_sign_in_detail.ssi_id
     *
     * @param ssiId the value for sis_sign_in_detail.ssi_id
     *
     * @mbg.generated Mon Aug 27 13:08:41 CST 2018
     */
    public void setSsiId(Integer ssiId) {
        this.ssiId = ssiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sis_sign_in_detail.su_id
     *
     * @return the value of sis_sign_in_detail.su_id
     *
     * @mbg.generated Mon Aug 27 13:08:41 CST 2018
     */
    public String getSuId() {
        return suId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sis_sign_in_detail.su_id
     *
     * @param suId the value for sis_sign_in_detail.su_id
     *
     * @mbg.generated Mon Aug 27 13:08:41 CST 2018
     */
    public void setSuId(String suId) {
        this.suId = suId == null ? null : suId.trim();
    }
}