package team.a9043.sign_in_system.pojo;

public class SisUserInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sis_user_info.su_id
     *
     * @mbg.generated Tue Sep 04 13:25:29 CST 2018
     */
    private String suId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sis_user_info.lack_num
     *
     * @mbg.generated Tue Sep 04 13:25:29 CST 2018
     */
    private Integer suiLackNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sis_user_info.su_id
     *
     * @return the value of sis_user_info.su_id
     * @mbg.generated Tue Sep 04 13:25:29 CST 2018
     */
    public String getSuId() {
        return suId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sis_user_info.su_id
     *
     * @param suId the value for sis_user_info.su_id
     * @mbg.generated Tue Sep 04 13:25:29 CST 2018
     */
    public void setSuId(String suId) {
        this.suId = suId == null ? null : suId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sis_user_info.lack_num
     *
     * @return the value of sis_user_info.lack_num
     * @mbg.generated Tue Sep 04 13:25:29 CST 2018
     */
    public Integer getSuiLackNum() {
        return suiLackNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sis_user_info.lack_num
     *
     * @param suiLackNum the value for sis_user_info.lack_num
     * @mbg.generated Tue Sep 04 13:25:29 CST 2018
     */
    public void setSuiLackNum(Integer suiLackNum) {
        this.suiLackNum = suiLackNum;
    }

    @Override
    public int hashCode() {
        return ("sisUserInfo_" + suId).hashCode();
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (!(obj instanceof SisUserInfo))
            return false;
        if (null == suId && null == (((SisUserInfo) obj).suId))
            return true;
        if (null == suId)
            return false;
        return suId.equals(((SisUserInfo) obj).suId);
    }
}