package team.a9043.sign_in_system_version_2.pojo;

import com.fasterxml.jackson.annotation.JsonInclude;

import java.util.List;

@JsonInclude(JsonInclude.Include.NON_NULL)
public class ManAbsRec {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column man_abs_rec_2017_true.mar_id
     *
     * @mbg.generated
     */
    private Integer marId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column man_abs_rec_2017_true.schedule_sch_id
     *
     * @mbg.generated
     */
    private Integer scheduleSchId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column man_abs_rec_2017_true.mar_week
     *
     * @mbg.generated
     */
    private Integer marWeek;

    private List<MarDtl> marDtlList;

    public List<MarDtl> getMarDtlList() {
        return marDtlList;
    }

    public ManAbsRec setMarDtlList(List<MarDtl> marDtlList) {
        this.marDtlList = marDtlList;
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column man_abs_rec_2017_true.mar_id
     *
     * @return the value of man_abs_rec_2017_true.mar_id
     * @mbg.generated
     */
    public Integer getMarId() {
        return marId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column man_abs_rec_2017_true.mar_id
     *
     * @param marId the value for man_abs_rec_2017_true.mar_id
     * @mbg.generated
     */
    public void setMarId(Integer marId) {
        this.marId = marId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column man_abs_rec_2017_true.schedule_sch_id
     *
     * @return the value of man_abs_rec_2017_true.schedule_sch_id
     * @mbg.generated
     */
    public Integer getScheduleSchId() {
        return scheduleSchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column man_abs_rec_2017_true.schedule_sch_id
     *
     * @param scheduleSchId the value for man_abs_rec_2017_true.schedule_sch_id
     * @mbg.generated
     */
    public void setScheduleSchId(Integer scheduleSchId) {
        this.scheduleSchId = scheduleSchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column man_abs_rec_2017_true.mar_week
     *
     * @return the value of man_abs_rec_2017_true.mar_week
     * @mbg.generated
     */
    public Integer getMarWeek() {
        return marWeek;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column man_abs_rec_2017_true.mar_week
     *
     * @param marWeek the value for man_abs_rec_2017_true.mar_week
     * @mbg.generated
     */
    public void setMarWeek(Integer marWeek) {
        this.marWeek = marWeek;
    }
}