package team.a9043.sign_in_system_version_2.pojo;

import com.fasterxml.jackson.annotation.JsonInclude;

import java.util.List;

@JsonInclude(JsonInclude.Include.NON_NULL)
public class Schedule {
    private Integer schSignInWeek;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.sch_id
     *
     * @mbg.generated
     */
    private Integer schId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.sch_year
     *
     * @mbg.generated
     */
    private Integer schYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.sch_term
     *
     * @mbg.generated
     */
    private Boolean schTerm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.sch_start_week
     *
     * @mbg.generated
     */
    private Integer schStartWeek;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.sch_end_week
     *
     * @mbg.generated
     */
    private Integer schEndWeek;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.sch_fortnight
     *
     * @mbg.generated
     */
    private Byte schFortnight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.sch_day
     *
     * @mbg.generated
     */
    private Integer schDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.sch_start_time
     *
     * @mbg.generated
     */
    private Integer schStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.sch_end_time
     *
     * @mbg.generated
     */
    private Integer schEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.course_coz_id
     *
     * @mbg.generated
     */
    private String courseCozId;

    private Location location;

    private List<Suspension> suspensionList;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.sch_id
     *
     * @return the value of schedule.sch_id
     * @mbg.generated
     */
    public Integer getSchId() {
        return schId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.sch_id
     *
     * @param schId the value for schedule.sch_id
     * @mbg.generated
     */
    public void setSchId(Integer schId) {
        this.schId = schId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.sch_year
     *
     * @return the value of schedule.sch_year
     * @mbg.generated
     */
    public Integer getSchYear() {
        return schYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.sch_year
     *
     * @param schYear the value for schedule.sch_year
     * @mbg.generated
     */
    public void setSchYear(Integer schYear) {
        this.schYear = schYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.sch_term
     *
     * @return the value of schedule.sch_term
     * @mbg.generated
     */
    public Boolean getSchTerm() {
        return schTerm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.sch_term
     *
     * @param schTerm the value for schedule.sch_term
     * @mbg.generated
     */
    public void setSchTerm(Boolean schTerm) {
        this.schTerm = schTerm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.sch_start_week
     *
     * @return the value of schedule.sch_start_week
     * @mbg.generated
     */
    public Integer getSchStartWeek() {
        return schStartWeek;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.sch_start_week
     *
     * @param schStartWeek the value for schedule.sch_start_week
     * @mbg.generated
     */
    public void setSchStartWeek(Integer schStartWeek) {
        this.schStartWeek = schStartWeek;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.sch_end_week
     *
     * @return the value of schedule.sch_end_week
     * @mbg.generated
     */
    public Integer getSchEndWeek() {
        return schEndWeek;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.sch_end_week
     *
     * @param schEndWeek the value for schedule.sch_end_week
     * @mbg.generated
     */
    public void setSchEndWeek(Integer schEndWeek) {
        this.schEndWeek = schEndWeek;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.sch_fortnight
     *
     * @return the value of schedule.sch_fortnight
     * @mbg.generated
     */
    public Byte getSchFortnight() {
        return schFortnight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.sch_fortnight
     *
     * @param schFortnight the value for schedule.sch_fortnight
     * @mbg.generated
     */
    public void setSchFortnight(Byte schFortnight) {
        this.schFortnight = schFortnight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.sch_day
     *
     * @return the value of schedule.sch_day
     * @mbg.generated
     */
    public Integer getSchDay() {
        return schDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.sch_day
     *
     * @param schDay the value for schedule.sch_day
     * @mbg.generated
     */
    public void setSchDay(Integer schDay) {
        this.schDay = schDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.sch_start_time
     *
     * @return the value of schedule.sch_start_time
     * @mbg.generated
     */
    public Integer getSchStartTime() {
        return schStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.sch_start_time
     *
     * @param schStartTime the value for schedule.sch_start_time
     * @mbg.generated
     */
    public void setSchStartTime(Integer schStartTime) {
        this.schStartTime = schStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.sch_end_time
     *
     * @return the value of schedule.sch_end_time
     * @mbg.generated
     */
    public Integer getSchEndTime() {
        return schEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.sch_end_time
     *
     * @param schEndTime the value for schedule.sch_end_time
     * @mbg.generated
     */
    public void setSchEndTime(Integer schEndTime) {
        this.schEndTime = schEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.course_coz_id
     *
     * @return the value of schedule.course_coz_id
     * @mbg.generated
     */
    public String getCourseCozId() {
        return courseCozId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.course_coz_id
     *
     * @param courseCozId the value for schedule.course_coz_id
     * @mbg.generated
     */
    public void setCourseCozId(String courseCozId) {
        this.courseCozId = courseCozId == null ? null : courseCozId.trim();
    }

    public Location getLocation() {
        return location;
    }

    public Schedule setLocation(Location location) {
        this.location = location;
        return this;
    }

    public Integer getSchSignInWeek() {
        return schSignInWeek;
    }

    public Schedule setSchSignInWeek(Integer schSignInWeek) {
        this.schSignInWeek = schSignInWeek;
        return this;
    }

    public List<Suspension> getSuspensionList() {
        return suspensionList;
    }

    public Schedule setSuspensionList(List<Suspension> suspensionList) {
        this.suspensionList = suspensionList;
        return this;
    }
}