package team.a9043.sign_in_system_version_2.pojo;

import com.fasterxml.jackson.annotation.JsonInclude;

import java.time.LocalDateTime;
import java.util.List;

@JsonInclude(JsonInclude.Include.NON_NULL)
public class SignIn {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign_in_2017_true.si_id
     *
     * @mbg.generated
     */
    private Integer siId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign_in_2017_true.si_week
     *
     * @mbg.generated
     */
    private Integer siWeek;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign_in_2017_true.si_time
     *
     * @mbg.generated
     */
    private LocalDateTime siTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign_in_2017_true.si_auto
     *
     * @mbg.generated
     */
    private Boolean siAuto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign_in_2017_true.schedule_sch_id
     *
     * @mbg.generated
     */
    private Integer scheduleSchId;

    private List<SignInRec> signInRecList;

    public List<SignInRec> getSignInRecList() {
        return signInRecList;
    }

    public SignIn setSignInRecList(List<SignInRec> signInRecList) {
        this.signInRecList = signInRecList;
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign_in_2017_true.si_id
     *
     * @return the value of sign_in_2017_true.si_id
     * @mbg.generated
     */
    public Integer getSiId() {
        return siId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign_in_2017_true.si_id
     *
     * @param siId the value for sign_in_2017_true.si_id
     * @mbg.generated
     */
    public void setSiId(Integer siId) {
        this.siId = siId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign_in_2017_true.si_week
     *
     * @return the value of sign_in_2017_true.si_week
     * @mbg.generated
     */
    public Integer getSiWeek() {
        return siWeek;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign_in_2017_true.si_week
     *
     * @param siWeek the value for sign_in_2017_true.si_week
     * @mbg.generated
     */
    public void setSiWeek(Integer siWeek) {
        this.siWeek = siWeek;
    }

    public LocalDateTime getSiTime() {
        return siTime;
    }

    public SignIn setSiTime(LocalDateTime siTime) {
        this.siTime = siTime;
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign_in_2017_true.si_auto
     *
     * @return the value of sign_in_2017_true.si_auto
     * @mbg.generated
     */
    public Boolean getSiAuto() {
        return siAuto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign_in_2017_true.si_auto
     *
     * @param siAuto the value for sign_in_2017_true.si_auto
     * @mbg.generated
     */
    public void setSiAuto(Boolean siAuto) {
        this.siAuto = siAuto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign_in_2017_true.schedule_sch_id
     *
     * @return the value of sign_in_2017_true.schedule_sch_id
     * @mbg.generated
     */
    public Integer getScheduleSchId() {
        return scheduleSchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign_in_2017_true.schedule_sch_id
     *
     * @param scheduleSchId the value for sign_in_2017_true.schedule_sch_id
     * @mbg.generated
     */
    public void setScheduleSchId(Integer scheduleSchId) {
        this.scheduleSchId = scheduleSchId;
    }
}