package team.a9043.sign_in_system_version_2.pojo;

import com.fasterxml.jackson.annotation.JsonInclude;
import team.a9043.sign_in_system_version_2.pojo.extend.ScheduleWithCozDtl;

@JsonInclude(JsonInclude.Include.NON_NULL)
public class Supervision {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supervision_2017_true.suv_id
     *
     * @mbg.generated
     */
    private Integer suvId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supervision_2017_true.suv_week
     *
     * @mbg.generated
     */
    private Integer suvWeek;

    private Integer scheduleSchId;

    private String userUsrId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supervision_2017_true.suv_leave
     *
     * @mbg.generated
     */
    private Boolean suvLeave;

    private Boolean record;

    private ScheduleWithCozDtl scheduleWithCozDtl;

    private User student;

    public ScheduleWithCozDtl getScheduleWithCozDtl() {
        return scheduleWithCozDtl;
    }

    public Supervision setScheduleWithCozDtl(ScheduleWithCozDtl scheduleWithCozDtl) {
        this.scheduleWithCozDtl = scheduleWithCozDtl;
        return this;
    }

    public User getStudent() {
        return student;
    }

    public Supervision setStudent(User student) {
        this.student = student;
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_2017_true.suv_id
     *
     * @return the value of supervision_2017_true.suv_id
     * @mbg.generated
     */
    public Integer getSuvId() {
        return suvId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_2017_true.suv_id
     *
     * @param suvId the value for supervision_2017_true.suv_id
     * @mbg.generated
     */
    public void setSuvId(Integer suvId) {
        this.suvId = suvId;
    }

    public String getUserUsrId() {
        return userUsrId;
    }

    public Supervision setUserUsrId(String userUsrId) {
        this.userUsrId = userUsrId;
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_2017_true.suv_week
     *
     * @return the value of supervision_2017_true.suv_week
     * @mbg.generated
     */
    public Integer getSuvWeek() {
        return suvWeek;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_2017_true.suv_week
     *
     * @param suvWeek the value for supervision_2017_true.suv_week
     * @mbg.generated
     */
    public void setSuvWeek(Integer suvWeek) {
        this.suvWeek = suvWeek;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supervision_2017_true.suv_leave
     *
     * @return the value of supervision_2017_true.suv_leave
     * @mbg.generated
     */
    public Boolean getSuvLeave() {
        return suvLeave;
    }

    public Integer getScheduleSchId() {
        return scheduleSchId;
    }

    public Supervision setScheduleSchId(Integer scheduleSchId) {
        this.scheduleSchId = scheduleSchId;
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supervision_2017_true.suv_leave
     *
     * @param suvLeave the value for supervision_2017_true.suv_leave
     * @mbg.generated
     */
    public void setSuvLeave(Boolean suvLeave) {
        this.suvLeave = suvLeave;
    }

    public Boolean getRecord() {
        return record;
    }

    public Supervision setRecord(Boolean record) {
        this.record = record;
        return this;
    }
}