package team.a9043.sign_in_system_version_2.pojo;

import com.fasterxml.jackson.annotation.JsonInclude;

@JsonInclude(JsonInclude.Include.NON_NULL)
public class SuvRec {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column suv_rec_2017_true.supervision_2017_true_suv_id
     *
     * @mbg.generated
     */
    private Integer supervisionSuvId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column suv_rec_2017_true.suv_rec_num
     *
     * @mbg.generated
     */
    private Integer suvRecNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column suv_rec_2017_true.suv_rec_bad_num
     *
     * @mbg.generated
     */
    private Integer suvRecBadNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column suv_rec_2017_true.suv_rec_name
     *
     * @mbg.generated
     */
    private String suvRecName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column suv_rec_2017_true.suv_rec_info
     *
     * @mbg.generated
     */
    private String suvRecInfo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column suv_rec_2017_true.supervision_2017_true_suv_id
     *
     * @return the value of suv_rec_2017_true.supervision_2017_true_suv_id
     *
     * @mbg.generated
     */
    public Integer getSupervisionSuvId() {
        return supervisionSuvId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column suv_rec_2017_true.supervision_2017_true_suv_id
     *
     * @param supervisionSuvId the value for suv_rec_2017_true.supervision_2017_true_suv_id
     *
     * @mbg.generated
     */
    public void setSupervisionSuvId(Integer supervisionSuvId) {
        this.supervisionSuvId = supervisionSuvId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column suv_rec_2017_true.suv_rec_num
     *
     * @return the value of suv_rec_2017_true.suv_rec_num
     *
     * @mbg.generated
     */
    public Integer getSuvRecNum() {
        return suvRecNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column suv_rec_2017_true.suv_rec_num
     *
     * @param suvRecNum the value for suv_rec_2017_true.suv_rec_num
     *
     * @mbg.generated
     */
    public void setSuvRecNum(Integer suvRecNum) {
        this.suvRecNum = suvRecNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column suv_rec_2017_true.suv_rec_bad_num
     *
     * @return the value of suv_rec_2017_true.suv_rec_bad_num
     *
     * @mbg.generated
     */
    public Integer getSuvRecBadNum() {
        return suvRecBadNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column suv_rec_2017_true.suv_rec_bad_num
     *
     * @param suvRecBadNum the value for suv_rec_2017_true.suv_rec_bad_num
     *
     * @mbg.generated
     */
    public void setSuvRecBadNum(Integer suvRecBadNum) {
        this.suvRecBadNum = suvRecBadNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column suv_rec_2017_true.suv_rec_name
     *
     * @return the value of suv_rec_2017_true.suv_rec_name
     *
     * @mbg.generated
     */
    public String getSuvRecName() {
        return suvRecName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column suv_rec_2017_true.suv_rec_name
     *
     * @param suvRecName the value for suv_rec_2017_true.suv_rec_name
     *
     * @mbg.generated
     */
    public void setSuvRecName(String suvRecName) {
        this.suvRecName = suvRecName == null ? null : suvRecName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column suv_rec_2017_true.suv_rec_info
     *
     * @return the value of suv_rec_2017_true.suv_rec_info
     *
     * @mbg.generated
     */
    public String getSuvRecInfo() {
        return suvRecInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column suv_rec_2017_true.suv_rec_info
     *
     * @param suvRecInfo the value for suv_rec_2017_true.suv_rec_info
     *
     * @mbg.generated
     */
    public void setSuvRecInfo(String suvRecInfo) {
        this.suvRecInfo = suvRecInfo == null ? null : suvRecInfo.trim();
    }
}