package team.a9043.sign_in_system_version_2.pojo;

import com.fasterxml.jackson.annotation.JsonInclude;

import java.io.Serializable;

@JsonInclude(JsonInclude.Include.NON_NULL)
public class User implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.usr_id
     *
     * @mbg.generated
     */
    private String usrId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.usr_name
     *
     * @mbg.generated
     */
    private String usrName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.usr_pwd
     *
     * @mbg.generated
     */
    private String usrPwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.usr_permit
     *
     * @mbg.generated
     */
    private Byte usrPermit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.open_id
     *
     * @mbg.generated
     */
    private String openId;

    public User(String usrId, String usrName, String usrPwd, Byte usrPermit, String openId) {
        this.usrId = usrId;
        this.usrName = usrName;
        this.usrPwd = usrPwd;
        this.usrPermit = usrPermit;
        this.openId = openId;
    }

    public User() {
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.usr_id
     *
     * @return the value of user.usr_id
     * @mbg.generated
     */
    public String getUsrId() {
        return usrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.usr_id
     *
     * @param usrId the value for user.usr_id
     * @mbg.generated
     */
    public void setUsrId(String usrId) {
        this.usrId = usrId == null ? null : usrId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.usr_name
     *
     * @return the value of user.usr_name
     * @mbg.generated
     */
    public String getUsrName() {
        return usrName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.usr_name
     *
     * @param usrName the value for user.usr_name
     * @mbg.generated
     */
    public void setUsrName(String usrName) {
        this.usrName = usrName == null ? null : usrName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.usr_pwd
     *
     * @return the value of user.usr_pwd
     * @mbg.generated
     */
    public String getUsrPwd() {
        return usrPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.usr_pwd
     *
     * @param usrPwd the value for user.usr_pwd
     * @mbg.generated
     */
    public void setUsrPwd(String usrPwd) {
        this.usrPwd = usrPwd == null ? null : usrPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.usr_permit
     *
     * @return the value of user.usr_permit
     * @mbg.generated
     */
    public Byte getUsrPermit() {
        return usrPermit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.usr_permit
     *
     * @param usrPermit the value for user.usr_permit
     * @mbg.generated
     */
    public void setUsrPermit(Byte usrPermit) {
        this.usrPermit = usrPermit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.open_id
     *
     * @return the value of user.open_id
     * @mbg.generated
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.open_id
     *
     * @param openId the value for user.open_id
     * @mbg.generated
     */
    public void setOpenId(String openId) {
        this.openId = openId == null ? null : openId.trim();
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == this) return true;

        if (!(obj instanceof User)) return false;

        return ((User) obj).usrId.equals(this.usrId) && ((User) obj).usrName.equals(this.usrName);

    }

    @Override
    public int hashCode() {
        return (this.usrId + "_" + this.usrName).hashCode();
    }
}